In [1]:
import torch


In [2]:
x = torch.arange(12)
x


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape


torch.Size([12])

In [5]:
x.numel() #元素的种数，张量

12

In [7]:
x = x.reshape(3, 4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
torch.tensor([[2,1,4,3],[1,2,3,4],[5,4,3,2]]) #创建数组、中括号个数代表了数组维度，此处为二维数组

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [5, 4, 3, 2]])

In [12]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x+y, x-y, x*y, x/y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [13]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [22]:
# 多个张量连结在一起
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((x, y), dim=0), torch.cat((x,y), dim=1) #按行合并和按列合并

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [23]:
#逻辑运算符构建二维张量
x  == y


tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [24]:
#对所有元素求和
x.sum()

tensor(66.)

In [25]:
#Broadcasting Mechanism

a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [26]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [29]:
print(x)
#访问最后一行，或者区间
x[-1], x[1:3]

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [28]:
x[1,2] #访问具体元素

tensor(6.)

In [32]:
x[0:2,:] =12
x #赋值

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [37]:
#执行一些操作导致为新结果分配内存
before = id(y)
y = y+x
id(y) == before
#before, id(y)

(2056072269376, 2056071968448)

In [40]:
# 执行原地操作，很明显，此处z的地址没有发生变化。因为这是对z内部的元素进行改写，而上一步则是产生了新的y
z = torch.zeros_like(y)
print('id(z):', id(z))
z[:] = x + y
print('id(z):', id(z))

id(z): 2056072046848
id(z): 2056072046848


In [41]:
#转换为NumPy张量
A = x.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [42]:
#将大小为1的张量转换为Python标量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [51]:
#数据预处理
#创建一个人工数据集，并存储在csv文件

import os

os.makedirs(os.path.join('d:/test', 'data'), exist_ok = True) #递归创建目录,默认写在用户文件夹下
data_file = os.path.join('d:/test', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms, Alley, price\n') #列明
    f.write('NA, Pave, 127500\n') #每行表示一个数据样本
    f.write('2, NA, 106000\n')
    f.write('4, NA, 178100\n')
    f.write('NA, NA, 140000\n')
    

In [65]:
#从csv文件中加载原始数据集

import pandas as pd

data = pd.read_csv(data_file)
print(data)


   NumRooms  Alley   price
0       NaN   Pave  127500
1       2.0     NA  106000
2       4.0     NA  178100
3       NaN     NA  140000


In [66]:
#处理缺失数据（插值和删除）
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean()) #利用平均数补足na
print(inputs)

   NumRooms  Alley
0       3.0   Pave
1       2.0     NA
2       4.0     NA
3       3.0     NA


In [67]:

#对于类别之和离散值，将NAN视为一个类别
inputs = pd.get_dummies(inputs, dummy_na = True)
print(inputs)

   NumRooms   Alley_ NA   Alley_ Pave   Alley_nan
0       3.0           0             1           0
1       2.0           1             0           0
2       4.0           1             0           0
3       3.0           1             0           0


In [69]:
#转化为张量
import torch

x,y = torch.tensor(inputs.values), torch.tensor(outputs.values)
x,y

(tensor([[3., 0., 1., 0.],
         [2., 1., 0., 0.],
         [4., 1., 0., 0.],
         [3., 1., 0., 0.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))